### ISSUE TITLE
Fix [warn] Cannot find Pi RPi.GPIO python library

### ISSUE THREAD

**Issue by RaymondMouthaan** [RaymondMouthaan/node-red-docker#11]
[solution](https://github.com/node-red/node-red-docker/issues/60#issuecomment-497988888)

- install gpio requirements
- test

**Comment by ernestgwilsonii** [comment]
Proposed solution:
```
pip install RPi.GPIO
```
See: https://github.com/ernestgwilsonii/docker-raspberry-pi-nodered/blob/master/Dockerfile.armhf

**Comment by RaymondMouthaan** [comment]
Thanks, ill add it asap!

**Comment by ernestgwilsonii** [comment]
It does add to the image size but it is well worth it on the raspberry pi platform to have this capability included by default IMHO.

**Comment by RaymondMouthaan** [comment]
@ernestgwilsonii, if it is only the python RPi.GPIO you require and therefore python and pip, you might consider [this](https://github.com/node-red/node-red-docker/issues/60#issuecomment-498008522), which is in my humble opinion a nicer solution in a Docker (swarm) solution. 

The Node-red container isn't "attached" to the Docker node where "things" are connected to it's gpio's. In other words node A as "things" connected to it's gpio's, while Node-Red runs on Docker node B.

From my point of view, all Node-Red images for all architectures should be identical and as small as possible. RPi.GPIO could be removed from Node-Red and if one wants to run on Raspberry PI they can use the above solution. However I am well aware of existing users that have there flows base on RPi.GPIO ...

I guess @knolleary, @dceejay and the others of team Node-Red eventually have to decide how to and what that add to the final official Node-Red images.

**Comment by dceejay** [comment]
Indeed GPIO was left out for that very reason. Certainly it would never be included in a minimal version.   As soon as you include it it drags in all the make dependancies and blows up the image size. The pi-gpiod solution is to my mind cleaner and does move the responsibility for the hardware IO to the host and leaves the docker with standard network connections which then allows sharing of the hardware if required. 

On a dedicated Pi image I can see it makes sense and indeed likewise for the PI preinstall (.deb) version we would also include them by default to make life easier for beginners.

**Comment by ernestgwilsonii** [comment]
In a dedicated Pi image and especially to help beginners for sure.

**Comment by RaymondMouthaan** [comment]
Ill close this issue, because it has been covered by branch [node-red-official](https://github.com/RaymondMouthaan/node-red-docker/tree/node-red-official)
