### ISSUE TITLE
Health check and time zone issues

### ISSUE THREAD

**Issue by fabnavigator** [RaymondMouthaan/node-red-docker#14]
First of all. Thank you so much for this image! I was dead in the water without it.

I have two node-red containers. In the first case, Portainer is telling me that the container is unhealthy, but I didn't add a health check. Below is my compose text. Could it have something to do with my non-standard port? I didn't see this issue with the nodered/node-red-docker:0.20.7-rpi image. Besides being unhealthy, my flows seem to be working.

node-red-bose:
container_name: node-red-bose
image: raymondmm/node-red:latest-rpi
# image: nodered/node-red-docker:0.20.7-rpi
user: '1001'
ports:
- 1881:1881
volumes:
- /home/fabnav/opt/node-red-bose:/data
- /etc/localtime:/etc/localtime:ro

Below is the log file:
,

node-red-docker@0.20.7 start /usr/src/node-red,
node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data",
,
18 Aug 12:54:34 - [info] ,
,
Welcome to Node-RED,
===================,
,
18 Aug 12:54:34 - [info] Node-RED version: v0.20.7,
18 Aug 12:54:34 - [info] Node.js version: v10.16.2,
18 Aug 12:54:34 - [info] Linux 4.19.58-v7+ arm LE,
18 Aug 12:54:35 - [info] Loading palette nodes,
18 Aug 12:54:38 - [info] Dashboard version 2.16.0 started at /ui,
18 Aug 12:54:39 - [info] Settings file : /data/settings.js,
18 Aug 12:54:39 - [info] Context store : 'default' [module=localfilesystem],
18 Aug 12:54:39 - [info] Context store : 'memory' [module=memory],
18 Aug 12:54:39 - [info] User directory : /data,
18 Aug 12:54:39 - [warn] Projects disabled : editorTheme.projects.enabled=false,
18 Aug 12:54:39 - [info] Flows file : /data/flows.json,
18 Aug 12:54:39 - [info] Server now running at http://127.0.0.1:1881/,
18 Aug 12:54:39 - [info] Starting flows,
18 Aug 12:54:39 - [info] Started flows,

My second container doesn't use a non-standard port, and isn't unhealthy. It uses timers though, and doesn't seem to be picking up the correct time zone, as the nodered/node-red-docker:0.20.7-rpi image did. Below is the compose text. I was able to get it to work by adding:
   environment:
      TZ: "America/New_York"
but I would expect other people are also using localtime like I was.

node-red:
container_name: node-red
image: raymondmm/node-red:latest-rpi
# image: nodered/node-red-docker:0.20.7-rpi
depends_on:
- postgres
- home-assistant
user: '1001'
ports:
- 1880:1880
volumes:
- /home/fabnav/opt/node-red:/data
- /etc/localtime:/etc/localtime:ro

Below is the log file:
,

node-red-docker@0.20.7 start /usr/src/node-red,
node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data",
,
18 Aug 13:18:35 - [info] ,
,
Welcome to Node-RED,
===================,
,
18 Aug 13:18:35 - [info] Node-RED version: v0.20.7,
18 Aug 13:18:35 - [info] Node.js version: v10.16.2,
18 Aug 13:18:35 - [info] Linux 4.19.58-v7+ arm LE,
18 Aug 13:18:36 - [info] Loading palette nodes,
18 Aug 13:18:41 - [info] Dashboard version 2.16.0 started at /ui,
18 Aug 13:18:41 - [info] Settings file : /data/settings.js,
18 Aug 13:18:41 - [info] Context store : 'default' [module=localfilesystem],
18 Aug 13:18:41 - [info] Context store : 'memory' [module=memory],
18 Aug 13:18:41 - [info] User directory : /data,
18 Aug 13:18:41 - [warn] Projects disabled : editorTheme.projects.enabled=false,
18 Aug 13:18:41 - [info] Flows file : /data/flows.json,
18 Aug 13:18:41 - [info] Server now running at http://127.0.0.1:1880/,
18 Aug 13:18:42 - [info] Starting flows,
18 Aug 13:18:42 - [info] [inject:18:00 on] crontab = 00 18 * * *,
18 Aug 13:18:42 - [info] [inject:20:00 on] crontab = 00 20 * * *,
18 Aug 13:18:42 - [info] [inject:01:30 off] crontab = 30 01 * * *,
18 Aug 13:18:42 - [info] [inject:6:00] crontab = 00 06 * * *,
18 Aug 13:18:42 - [info] [inject:5:00] crontab = 00 05 * * *,
18 Aug 13:18:42 - [info] [inject:9:00 on] crontab = 00 09 * * *,
18 Aug 13:18:42 - [info] [inject:daily initialization to false] crontab = 00 18 * * *,
18 Aug 13:18:42 - [info] [inject:19:00] crontab = 00 19 * * *,
18 Aug 13:18:42 - [info] [inject:22:00] crontab = 00 22 * * *,
18 Aug 13:18:43 - [info] [inject:midnight] crontab = 01 00 * * *,
18 Aug 13:18:43 - [info] Started flows,
18 Aug 13:18:43 - [info] [server:Home Assistant] WebSocket Connected to http://home-assistant:8123,

Thanks,

Bill

**Comment by RaymondMouthaan** [comment]
Hi @fabnavigator,

First of all, why do you want to change the internal port of node-red? .. the issue is that the build-in health_check checks http//localhost:**1880** and not 1881. If you want to change the external port, thats fine, just do -p1890:1880 or something similar.

Regarding the timezone in the container, just use `TZ=America/New_York` - using volume binding to `/etc/localtime:/etc/localtime:ro` is a less cleaner way.

**Comment by fabnavigator** [comment]
In my defense, I thought this image would behave the same as the 0.20.8-rpi image without me having to change my compose file. I imagine others will also have these issues.

When I change to 1881:1880, I can't navigate to my page on port 1881, and is still marked as unhealthy. Shouldn't be up to me to decide if I want to add a health check to the container, as opposed to having no choice?

I don't agree that the volume binding is less cleaner. With volume binding I change the TZ in one place (in unix config), as opposed to having to change it multiple places, if I hardcode it in the compose file.

I hope I don't sound ungrateful. You have really helped me out here.

**Comment by RaymondMouthaan** [comment]
Hi @fabnavigator 

Please find below my testing results.

## Unhealthy
I did some testing, but i can't reproduce the unhealthy container. I've created some new images where the Health check timeout has been increased - this might fixing it for you too.

Her is my docker run command:

`docker run -it -p1888:1880 --name node-red-testing raymondmm/node-red:testing`

```
> node-red-docker@0.20.7 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"

18 Aug 15:20:06 - [info] 

Welcome to Node-RED
===================

18 Aug 15:20:06 - [info] Node-RED version: v0.20.7
18 Aug 15:20:06 - [info] Node.js  version: v10.16.3
18 Aug 15:20:06 - [info] Linux 4.19.58-v7+ arm LE
18 Aug 15:20:07 - [info] Loading palette nodes
18 Aug 15:20:12 - [info] Settings file  : /data/settings.js
18 Aug 15:20:12 - [info] Context store  : 'default' [module=memory]
18 Aug 15:20:12 - [info] User directory : /data
18 Aug 15:20:12 - [warn] Projects disabled : editorTheme.projects.enabled=false
18 Aug 15:20:12 - [info] Flows file     : /data/flows.json
18 Aug 15:20:12 - [info] Creating new flow file
18 Aug 15:20:12 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

18 Aug 15:20:12 - [info] Server now running at http://127.0.0.1:1880/
18 Aug 15:20:12 - [info] Starting flows
18 Aug 15:20:12 - [info] Started flows
```

![Screen Shot 2019-08-18 at 17 21 25](https://user-images.githubusercontent.com/25717738/63226652-a95e3480-c1dc-11e9-8ca1-57ec44570b20.png)

## Localtime & Timezone
### Localtime only
The logging displays the wrong time, it should be + 2 hours. However when logging into the running container - `date` command gives the correct time. Requesting the `date` from the exec node also returns the correct time. 

`docker run -it -p1888:1880 -v /etc/localtime:/etc/localtime:ro --name node-red-testing raymondmm/node-red:testing`

```
> node-red-docker@0.20.7 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"

18 Aug 15:25:15 - [info] 

Welcome to Node-RED
===================

18 Aug 15:25:15 - [info] Node-RED version: v0.20.7
18 Aug 15:25:15 - [info] Node.js  version: v10.16.3
18 Aug 15:25:15 - [info] Linux 4.19.58-v7+ arm LE
18 Aug 15:25:16 - [info] Loading palette nodes
18 Aug 15:25:20 - [info] Settings file  : /data/settings.js
18 Aug 15:25:20 - [info] Context store  : 'default' [module=memory]
18 Aug 15:25:20 - [info] User directory : /data
18 Aug 15:25:20 - [warn] Projects disabled : editorTheme.projects.enabled=false
18 Aug 15:25:20 - [info] Flows file     : /data/flows.json
18 Aug 15:25:20 - [info] Creating new flow file
18 Aug 15:25:20 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

18 Aug 15:25:20 - [info] Server now running at http://127.0.0.1:1880/
18 Aug 15:25:20 - [info] Starting flows
18 Aug 15:25:20 - [info] Started flows
```

![Screen Shot 2019-08-18 at 17 30 04](https://user-images.githubusercontent.com/25717738/63226718-e1b24280-c1dd-11e9-975d-d4d1f3e66dc9.png)

![Screen Shot 2019-08-18 at 17 34 37](https://user-images.githubusercontent.com/25717738/63226761-7c128600-c1de-11e9-9815-2cac75a59722.png)

### Localtime + Timezone
I did above tests also with timezone as volume binding, with the same results.

`docker run -it -p1888:1880 -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro --name node-red-testing raymondmm/node-red:testing`

I have no idea why the logging (seems to me only the wrong time has effect on the logging) doesn't respect the time set by the volume binding.

###  TZ=Europe/Amsterdam 
Just to compleet the test:

`docker run -it -p1888:1880 -e TZ=Europe/Amsterdam --name node-red-testing raymondmm/node-red:testing`

```
> node-red-docker@0.20.7 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"

18 Aug 17:39:20 - [info] 

Welcome to Node-RED
===================

18 Aug 17:39:20 - [info] Node-RED version: v0.20.7
18 Aug 17:39:20 - [info] Node.js  version: v10.16.3
18 Aug 17:39:20 - [info] Linux 4.19.58-v7+ arm LE
18 Aug 17:39:21 - [info] Loading palette nodes
18 Aug 17:39:26 - [info] Settings file  : /data/settings.js
18 Aug 17:39:26 - [info] Context store  : 'default' [module=memory]
18 Aug 17:39:26 - [info] User directory : /data
18 Aug 17:39:26 - [warn] Projects disabled : editorTheme.projects.enabled=false
18 Aug 17:39:26 - [info] Flows file     : /data/flows.json
18 Aug 17:39:26 - [info] Creating new flow file
18 Aug 17:39:26 - [warn] 

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

18 Aug 17:39:26 - [info] Server now running at http://127.0.0.1:1880/
18 Aug 17:39:26 - [info] Starting flows
18 Aug 17:39:26 - [info] Started flows
```

Hopes this helps and if you have any suggestions, please let me know :)

**Comment by RaymondMouthaan** [comment]
[**update**] In the latest testing images i have removed the health check, it gave on a certain container several  time a status `complete`.

**Comment by fabnavigator** [comment]
Hi Raymond,

### Unhealthy
I verify that the health check is no longer there. Thank you.

### Localtime & Timezone
#### Localtime
I get exactly the same results as you do, except my log time is +4 hours. The one test you didn't do, is to actually set the injection node for a time, and see that it fires at the correct time. My node does not fire at the correct time.
#### Timezone
The log has the correct time and when I set the injection node to a time, it fires at the correct time.

Thanks,

Bill

**Comment by RaymondMouthaan** [comment]
Hi Billy, 

Thanks for testing the node-red images 👍 

`docker run -it --rm -p2000:1880 -e TZ=Europe/Amsterdam raymondmm/node-red:testing`

- [ √ ] displays the correct time in the logging
- [ √ ] displays the correct time after logging into the container with `docker exec ... `
- [ √ ] an inject node at a specific time does get trigger at the right time and the debug shows the injected timestamp (clicking it changes the way it is display) and also the date/time of the debug message shows correctly.

![Screen Shot 2019-08-19 at 00 15 24](https://user-images.githubusercontent.com/25717738/63231072-8781a380-c216-11e9-99dc-7513b4e7823a.png)


`docker run -it --rm -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro -p 2000:1880 raymondmm/node-red:testing`

- [ X ] displays the wrong time in the logging
- [ √ ] displays the correct time after logging into the container with `docker exec ... `
- [ X ] an inject node at a specific time does **not** get trigger at the right time. Manual trigging it does show the injected timestamp (clicking it changes the way it is display) and also the date/time of the debug message shows correctly.

Seems to me that TZ=Europe/Amsterdam works best, must be something within Node-RED or perhaps NodeJS how it handles the time/date. I can't tell, maybe one of the Node-RED team (@knolleary) does know the answer/solution? 

Cheers,
Ray

**Comment by fabnavigator** [comment]
Hi Ray,

My pleasure.

Maybe this is a silly suggestion, but what if you creates another testing version that has node.js v8, but no other changes. Then we could see if localtime works?

Best regards,

Bill

**Comment by RaymondMouthaan** [comment]
Hi Bill,

Turns out that the node8 alpine base image doesn't have tzdata installed and therefore `-e TZ=Europe/Amsterdam` didn't set the correct time and date, after installing tzdata it worked.

Regarding `-v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro` that didn't work at all ...

**Comment by RaymondMouthaan** [comment]
@fabnavigator, i haven't fixed the issue regarding  /etc/localtime:/etc/localtime but last weekend i've been working on a new approach for the naming of tags and so on ... 

`raymondmm/node-red:testing` no longer exists, the one i recommend to use is : `raymondmm/node-red:latest`, look [here](https://github.com/RaymondMouthaan/node-red-docker#image-variations) if you want to know the details :)

Regards,
Ray
